---
name: categorize_duo_chat_question
description: This should not be an unit primitive. It is used to categorize user questions for the purpose of product analytics.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::duo_chat
feature_category: duo_chat
documentation_url: https://docs.gitlab.com/development/ai_features/duo_chat/#product-analysis
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_pro
  - duo_enterprise
  - duo_core