---
name: code_suggestions
description: Helps you write code more efficiently by generating code and showing suggestions as you type.
cut_off_date: 2024-02-15T00:00:00+00:00
min_gitlab_version: '16.8'
group: group::code suggestions
feature_category: code_suggestions
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#code-suggestions
deprecated_by_url: https://gitlab.com/gitlab-org/cloud-connector/gitlab-cloud-connector/-/merge_requests/47
deprecation_message: This unit primitive is deprecated, please use code_create or code_generate unit primitives.
backend_services:
  - ai_gateway
add_ons:
  - duo_pro
  - duo_enterprise
