---
name: description_composer
description: Composes a description for a merge request.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::code review
feature_category: code_review_workflow
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/183512
backend_services:
  - ai_gateway
add_ons:
  - duo_enterprise
