---
name: explain_vulnerability
description: Explain a security vulnerability of the given CVE or code.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::threat insights
feature_category: vulnerability_management
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#vulnerability-explanation
introduced_by_url: https://gitlab.com/gitlab-org/customers-gitlab-com/-/merge_requests/10344
unit_primitive_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470958
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
