---
name: generate_code
description: Helps you write code more efficiently by generating code as you type.
cut_off_date: 2024-02-15T00:00:00+00:00
min_gitlab_version: "16.8"
unit_primitive_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/497813
introduced_by_url: https://gitlab.com/gitlab-org/cloud-connector/gitlab-cloud-connector/-/merge_requests/46
documentation_url: https://docs.gitlab.com/ee/user/project/repository/code_suggestions/#code-generation
group: group::code suggestions
feature_category: code_suggestions
backend_services:
  - ai_gateway
add_ons:
  - duo_pro
  - duo_enterprise
  - duo_core
