---
name: generate_commit_message
description: Generate a Git commit message.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::code creation
feature_category: code_review_workflow
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#merge-commit-message-generation
introduced_by_url: https://gitlab.com/gitlab-org/customers-gitlab-com/-/merge_requests/10371
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
