---
name: glab_ask_git_command
description: Discover or recall git commands when and where you need them.
cut_off_date: 2024-10-17T00:00:00+00:00
min_gitlab_version: '17.2'
group: group::code review
feature_category: code_review_workflow
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#gitlab-duo-for-the-cli
introduced_by_url: https://gitlab.com/gitlab-org/customers-gitlab-com/-/merge_requests/10298
backend_services:
  - ai_gateway
add_ons:
  - duo_enterprise
