---
name: include_terminal_context
description: Include terminal context in the prompt.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::duo_chat
feature_category: duo_chat
documentation_url: "" # To be added: https://gitlab.com/gitlab-org/gitlab/-/issues/504104
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_pro
  - duo_enterprise
  - duo_core
