---
name: include_local_git_context
description: Include local git context (Git Diffs/Commits) in the prompt.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::duo_chat
feature_category: duo_chat
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/172401
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
