---
name: refactor_code
description: Refactor the selected code.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::duo_chat
feature_category: duo_chat
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#refactor-code
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
  - duo_pro
  - duo_core
