---
name: resolve_vulnerability
description: Write code that fixes the vulnerability.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::threat insights
feature_category: vulnerability_management
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#vulnerability-resolution
introduced_by_url: https://gitlab.com/gitlab-org/customers-gitlab-com/-/merge_requests/10457
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
