---
name: summarize_review
description: Summarize open reviews in merge requests.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::code review
feature_category: code_review_workflow
documentation_url: https://docs.gitlab.com/ee/user/gitlab_duo/#code-review-summary
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
