---
name: summarize_comments
description: Summarize comments of the issue or epic.
cut_off_date: 2024-10-17T00:00:00+00:00
group: group::project management
feature_category: team_planning
backend_services:
  - ai_gateway
  - duo_workflow_service
add_ons:
  - duo_enterprise
