---
name: update_vulnerability_severity
description: Update severity level of the vulnerability.
documentation_url: https://docs.gitlab.com/user/application_security/triage/#update-vulnerability-severity-using-duo
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/2994
group: group::security_insights
cut_off_date: 2025-07-03T00:00:00+00:00
feature_category: vulnerability_management
backend_services:
  - duo_workflow_service
add_ons:
  - duo_enterprise
